backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "insight"
    label: "Insights"
    folder: "src/lib/_content/insights"
    create: true
    slug: "{{title}}-{{day}}-{{month}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Author", name: "author", widget: "text" }
      - { label: "Post", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
  - name: "releases"
    label: "Releases"
    folder: "src/lib/_content/releases"
    create: true
    slug: "{{artist}}-{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Artist", name: "artist", widget: "string" }
      - { label: "Release Date", name: "date", widget: "datetime" }
      - { label: "Cover Art", name: "cover_art", widget: "image"}
      - { label: "Buy/Stream Link", name: "buy_link", widget: "string"}
      - { label: "Embed Player Snippet", name: "embed_snippet", widget: "markdown" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }